#!/bin/sh

DAEMON_NAME="aesdsocket_main"
DAEMON_DIR=$(dirname "$(realpath "$0")")
DAEMON_PATH="$DAEMON_DIR/$DAEMON_NAME"
PIDFILE="/var/run/$DAEMON_NAME.pid"

if [ "$1" = "-d" ]; then
    # Run as daemon using start-stop-daemon
    start-stop-daemon -S --background -d $DAEMON_DIR --exec $DAEMON_PATH
else
    # Run normally
    $DAEMON_PATH
fi
